package net.comes.care.ws.sycare;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-01T12:52:24.759+02:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl", name = "sycare")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-08-01T12:52:24.759+02:00", comments = "Apache CXF 2.6.1")
public interface Sycare {

    /**
     * Client sends data for available devices to Webservice. We return a status.
     */
    @WebResult(name = "Status", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl", partName = "parameters")
    @WebMethod(action = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl/sendData")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-08-01T12:52:24.759+02:00")
    public Status sendData(
        @WebParam(partName = "parameters", name = "sendDataRequest", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl")
        SendDataRequest parameters
    );

    /**
     * Client has to authenticate against Webservice with username and password.
     * 			If account exists we will return an appropriate userid. 
     * 			If authentication takes place within a configurable period before password expires,
     * 			we return the  additional parameter PwdExpire with the date of expiration as value. 
     * 			If account doesn't exist we return zero.
     * 		
     */
    @WebResult(name = "Session", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl", partName = "parameters")
    @WebMethod(action = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl/authenticate")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-08-01T12:52:24.759+02:00")
    public Session authenticate(
        @WebParam(partName = "parameters", name = "Credentials", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl")
        Credentials parameters
    );

    /**
     * Client sends request for retrieving next available survey
     */
    @WebResult(name = "aSurvey", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl", partName = "parameters")
    @WebMethod(action = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl/getSurvey")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-08-01T12:52:24.759+02:00")
    public ASurvey getSurvey(
        @WebParam(partName = "parameters", name = "getSurveyRequest", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl")
        GetSurveyRequest parameters
    );

    /**
     * Client sends new password.
     * 			We return if password is valid and could be inserted in database succesfully.
     * 		
     */
    @WebResult(name = "Status", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl", partName = "parameters")
    @WebMethod(action = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl/newPwd")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-08-01T12:52:24.759+02:00")
    public Status newPwd(
        @WebParam(partName = "parameters", name = "newPwdRequest", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl")
        NewPwdRequest parameters
    );

    /**
     * Client sends request for retrieving status of messages and/or surveys and/or a specific device.
     * 			We return the status of the devices which contains requested device identifier and most recent values for devices
     * 			and/or the number of the unread messages and/or the number of the unread surveys.
     * 			Returns a SOAP-Fault if no session id is transmitted, session id is invalid or session is expired.
     * 		
     */
    @WebResult(name = "Status", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl", partName = "parameters")
    @WebMethod(action = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl/getStatus")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-08-01T12:52:24.759+02:00")
    public Status getStatus(
        @WebParam(partName = "parameters", name = "getStatusRequest", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl")
        GetStatusRequest parameters
    );

    /**
     * Client sends device type. We return a list of manufacturers for this device type.
     *     		The list is empty, if no devices of given type are allocated to actual patient.
     *     	
     */
    @WebResult(name = "DeviceManufacturers", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl", partName = "parameters")
    @WebMethod(action = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl/getDeviceManufacturers")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-08-01T12:52:24.759+02:00")
    public DeviceManufacturers getDeviceManufacturers(
        @WebParam(partName = "parameters", name = "getDeviceManufacturersRequest", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl")
        GetDeviceManufacturersRequest parameters
    );

    /**
     * Client sends device type and number of days.
     *     		The number of days specfies how many days before current date the period 
     * 			from which the measured data shall come begins.  
     * 			We return measured data for specified device type within specified period.
     * 		
     */
    @WebResult(name = "getMeasuredDataResponse", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl", partName = "parameters")
    @WebMethod(action = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl/getMeasuredData")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-08-01T12:52:24.759+02:00")
    public GetMeasuredDataResponse getMeasuredData(
        @WebParam(partName = "parameters", name = "getMeasuredDataRequest", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl")
        GetMeasuredDataRequest parameters
    );

    /**
     * Client sends confirmation and maybe answers of a survey. 
     * 			We return if data could be inserted in database succesfully
     * 		
     */
    @WebResult(name = "Status", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl", partName = "parameters")
    @WebMethod(action = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl/sendSurveyData")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-08-01T12:52:24.759+02:00")
    public Status sendSurveyData(
        @WebParam(partName = "parameters", name = "sendSurveyDataRequest", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl")
        SendSurveyDataRequest parameters
    );

    /**
     * Client sends request for retrieving next available message
     */
    @WebResult(name = "aMessage", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl", partName = "parameters")
    @WebMethod(action = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl/getMessage")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-08-01T12:52:24.759+02:00")
    public AMessage getMessage(
        @WebParam(partName = "parameters", name = "getMessageRequest", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl")
        GetMessageRequest parameters
    );

    /**
     * Client sends request for embedded device types. We return a list of device types.
     */
    @WebResult(name = "DeviceTypes", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl", partName = "parameters")
    @WebMethod(action = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl/getDeviceTypes")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-08-01T12:52:24.759+02:00")
    public DeviceTypes getDeviceTypes(
        @WebParam(partName = "parameters", name = "getDeviceTypesRequest", targetNamespace = "http://www.kompass-lme.ei.tum.de/sycare/soap/sycare-0.11.wsdl")
        GetDeviceTypesRequest parameters
    );
}
