
package net.comes.care.ws.sycare.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-05-16T15:17:52.154+02:00
 * Generated source version: 2.6.0
 * 
 */
public final class Sycare_SycareSOAP_Client {

    private static final QName SERVICE_NAME = new QName("https://comes.synergysystems-net.com/sycare/soap/sycare-0.11.wsdl", "sycare");

    private Sycare_SycareSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Sycare_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Sycare_Service ss = new Sycare_Service(wsdlURL, SERVICE_NAME);
        Sycare port = ss.getSycareSOAP();  
        
        {
        System.out.println("Invoking authenticate...");
        net.comes.care.ws.sycare.Credentials _authenticate_parameters = null;
        net.comes.care.ws.sycare.Session _authenticate__return = port.authenticate(_authenticate_parameters);
        System.out.println("authenticate.result=" + _authenticate__return);


        }
        {
        System.out.println("Invoking getMessage...");
        net.comes.care.ws.sycare.GetMessageRequest _getMessage_parameters = null;
        net.comes.care.ws.sycare.AMessage _getMessage__return = port.getMessage(_getMessage_parameters);
        System.out.println("getMessage.result=" + _getMessage__return);


        }
        {
        System.out.println("Invoking getDeviceManufacturers...");
        net.comes.care.ws.sycare.GetDeviceManufacturersRequest _getDeviceManufacturers_parameters = null;
        net.comes.care.ws.sycare.DeviceManufacturers _getDeviceManufacturers__return = port.getDeviceManufacturers(_getDeviceManufacturers_parameters);
        System.out.println("getDeviceManufacturers.result=" + _getDeviceManufacturers__return);


        }
        {
        System.out.println("Invoking sendSurveyData...");
        net.comes.care.ws.sycare.SendSurveyDataRequest _sendSurveyData_parameters = null;
        net.comes.care.ws.sycare.Status _sendSurveyData__return = port.sendSurveyData(_sendSurveyData_parameters);
        System.out.println("sendSurveyData.result=" + _sendSurveyData__return);


        }
        {
        System.out.println("Invoking newPwd...");
        net.comes.care.ws.sycare.NewPwdRequest _newPwd_parameters = null;
        net.comes.care.ws.sycare.Status _newPwd__return = port.newPwd(_newPwd_parameters);
        System.out.println("newPwd.result=" + _newPwd__return);


        }
        {
        System.out.println("Invoking getMeasuredData...");
        net.comes.care.ws.sycare.GetMeasuredDataRequest _getMeasuredData_parameters = null;
        net.comes.care.ws.sycare.GetMeasuredDataResponse _getMeasuredData__return = port.getMeasuredData(_getMeasuredData_parameters);
        System.out.println("getMeasuredData.result=" + _getMeasuredData__return);


        }
        {
        System.out.println("Invoking sendData...");
        net.comes.care.ws.sycare.SendDataRequest _sendData_parameters = null;
        net.comes.care.ws.sycare.Status _sendData__return = port.sendData(_sendData_parameters);
        System.out.println("sendData.result=" + _sendData__return);


        }
        {
        System.out.println("Invoking getDeviceTypes...");
        net.comes.care.ws.sycare.GetDeviceTypesRequest _getDeviceTypes_parameters = null;
        net.comes.care.ws.sycare.DeviceTypes _getDeviceTypes__return = port.getDeviceTypes(_getDeviceTypes_parameters);
        System.out.println("getDeviceTypes.result=" + _getDeviceTypes__return);


        }
        {
        System.out.println("Invoking getStatus...");
        net.comes.care.ws.sycare.GetStatusRequest _getStatus_parameters = null;
        net.comes.care.ws.sycare.Status _getStatus__return = port.getStatus(_getStatus_parameters);
        System.out.println("getStatus.result=" + _getStatus__return);


        }
        {
        System.out.println("Invoking getSurvey...");
        net.comes.care.ws.sycare.GetSurveyRequest _getSurvey_parameters = null;
        net.comes.care.ws.sycare.ASurvey _getSurvey__return = port.getSurvey(_getSurvey_parameters);
        System.out.println("getSurvey.result=" + _getSurvey__return);


        }

        System.exit(0);
    }

}
